### ISSUE TITLE
Bounds error in NPS accelerometer simulation for ARDrone2

### ISSUE THREAD

**Issue by tomvand** [paparazzi/paparazzi#2090]
I have found a possible bug in the nps accelerometer model or the nps sensor parameters for the ARDrone2:

In [`nps_sensor_accel.c`](https://github.com/paparazzi/paparazzi/blob/master/sw/simulator/nps/nps_sensor_accel.c#L39), the accelerometer values are *first* offset by their neutral value `NPS_ACCEL_NEUTRAL_X/Y/Z` (equal to `IMU_ACCEL_X/Y/Z_NEUTRAL` = 2048 as set in the airframe file) in line 39 before being saturated in line 56.

In [`nps_sensors_params_ardrone2.h`](https://github.com/paparazzi/paparazzi/blob/master/conf/simulator/nps/nps_sensors_params_ardrone2.h#L38), however, the bounds `NPS_ACCEL_MIN/MAX` do not seem to take this offset into account. In fact, the upper bound `NPS_ACCEL_MAX` (=2047) is smaller than the neutral value `NPS/IMU_ACCEL_X/Y/Z_NEUTRAL` (=2048). This causes the the accelerometer to saturate, especially when it already has an offset from `BODY_TO_IMU`.

As far as I see it, the bounds in [`nps_sensors_params_ardrone2.h`](https://github.com/paparazzi/paparazzi/blob/master/conf/simulator/nps/nps_sensors_params_ardrone2.h#L38) should be set to
```
#define NPS_ACCEL_MIN 0;
#define NPS_ACCEL_MAX 4095;
```
Can anyone confirm this?

**Comment by OpenUAS** [comment]
Assigned to self to see to validate fix proposed. Thx @tomvand for investigating

**Comment by kirkscheper** [comment]
Should be addressed with #2120

**Comment by tomvand** [comment]
#2120 has not fixed the problem (it also did not change nps_sensors_params_ardrone2.h), checked by plotting the scaled sensor values:
![imu_error](https://user-images.githubusercontent.com/5869151/31772075-a48f2624-b4de-11e7-8386-3448844de85d.png)

**Comment by kirkscheper** [comment]
Indeed, I had it in my branch but forgot to add it to the PR. tnx for the review.
