### ISSUE TITLE
bebop2_opticflow segfault at takeoff

### ISSUE THREAD

**Issue by tomvand** [paparazzi/paparazzi#2294]
Tested with commit da3e040

When taking off with the example bebop2_opticflow aircraft, the autopilot crashes with a segfault. The segfault appears to occur only after takeoff (during the initial climb). The segfault can also be triggered by manually lifting the drone from the ground (with motors killed. It may take a few attempts to trigger the crash). Just unkilling the motors on the ground does not seem to trigger the segfault.

The example bebop2 aircraft without optical flow does not run into a segfault. I suspect this is an optical flow problem.

**Comment by tomvand** [comment]
I can replicate this crash with commit 30ab12 but not with a628e6 (the one before that), so that's when something went wrong it seems.

**Comment by guidoAI** [comment]
I could not reproduce the problem, although I tried... The mentioned airframe was indeed not working well though. See the pull request: https://github.com/paparazzi/paparazzi/pull/2297

**Comment by tomvand** [comment]
I tried your pull request #2297, but it does not fix the segfault. I'll try your derotation_threshold branch next.

**Comment by tomvand** [comment]
Not a 100% sure about this or how it would work, but the problem seems easier to reproduce after killing and unkilling the drone a few times.

**Comment by tomvand** [comment]
Tested on a second Bebop2 with the same results.

Managed to get gdbserver working on the Bebop2, but no conclusive results yet. For completeness:
```
Starting program: /home/tom/paparazzi/var/aircrafts/bebop2_opticflow/ap/ap.elf 
[New Thread 1359.1372]
[Switching to Thread 1359.1372]
0x000452f4 in image_to_grayscale ()
(gdb) bt
#0  0x000452f4 in image_to_grayscale ()
#1  0x00048758 in calc_fast9_lukas_kanade ()
#2  0x0004abe8 in opticflow_calc_frame ()
#3  0x0004afc8 in opticflow_module_calc ()
#4  0x00038094 in cv_run_device ()
#5  0x0004ba64 in video_thread_function ()
#6  0x000a8b04 in start_thread ()
#7  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

(gdb) thread apply all bt
[New Thread 1359.1366]
[New Thread 1359.1367]
[New Thread 1359.1368]
[New Thread 1359.1369]
[New Thread 1359.1370]
[New Thread 1359.1371]
[New Thread 1359.1373]

Thread 9 (Thread 1359.1373):
#0  0x000cbed4 in select ()
#1  0x000cd39c in __libc_enable_asynccancel ()
#2  0x00000000 in ?? ()

Thread 8 (Thread 1359.1371):
#0  0x000cb864 in poll ()
#1  0x000cd39c in __libc_enable_asynccancel ()
#2  0x43ea6d00 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 7 (Thread 1359.1370):
#0  0x000cbed4 in select ()
#1  0x000cd39c in __libc_enable_asynccancel ()
#2  0x00000000 in ?? ()

Thread 6 (Thread 1359.1369):
#0  0x000ac248 in pthread_cond_wait ()
#1  0x00010c6c in i2c_thread ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 5 (Thread 1359.1368):
#0  0x000cbdfc in ioctl ()
#1  0x00010b6c in i2c_thread ()
#2  0x000a8b04 in start_thread ()
---Type <return> to continue, or q <return> to quit---
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 4 (Thread 1359.1367):
#0  0x000ac248 in pthread_cond_wait ()
#1  0x00010c6c in i2c_thread ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 3 (Thread 1359.1366):
#0  0x000ad310 in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00011670 in sys_time_thread_main ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 2 (Thread 1359.1372):
#0  0x000452f4 in image_to_grayscale ()
#1  0x00048758 in calc_fast9_lukas_kanade ()
#2  0x0004abe8 in opticflow_calc_frame ()
#3  0x0004afc8 in opticflow_module_calc ()
#4  0x00038094 in cv_run_device ()
#5  0x0004ba64 in video_thread_function ()
#6  0x000a8b04 in start_thread ()
#7  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

---Type <return> to continue, or q <return> to quit---
Thread 1 (Thread 1359.1359):
#0  0x0003761c in i2c_blocking_transceive ()
#1  0x00014cc0 in actuators_bebop_commit ()
#2  0x00022948 in main_periodic ()
#3  0x000268b8 in handle_periodic_tasks ()
#4  0x00010458 in main () at firmwares/rotorcraft/main.c:69

--------------------------------------------------------------------------------

Starting program: /home/tom/paparazzi/var/aircrafts/bebop2_opticflow/ap/ap.elf 
[New Thread 1382.1397]
[Switching to Thread 1382.1397]
0x000c8144 in strlen ()
(gdb) bt
#0  0x000c8144 in strlen ()
#1  0x000e087c in vfprintf ()
#2  0x000cdd4c in __printf_chk ()
#3  0x04f394bc in ?? ()
Backtrace stopped: frame did not save the PC

(gdb) thread apply all bt
[New Thread 1382.1389]
[New Thread 1382.1390]
[New Thread 1382.1391]
[New Thread 1382.1392]
[New Thread 1382.1393]
[New Thread 1382.1395]
[New Thread 1382.1396]

Thread 9 (Thread 1382.1396):
#0  0x00045ee0 in image_difference ()
#1  0x00047370 in opticFlowLK ()
#2  0x00048a00 in calc_fast9_lukas_kanade ()
#3  0x0004abe8 in opticflow_calc_frame ()
#4  0x0004afc8 in opticflow_module_calc ()
#5  0x00038094 in cv_run_device ()
#6  0x0004ba64 in video_thread_function ()
#7  0x000a8b04 in start_thread ()
#8  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 8 (Thread 1382.1395):
#0  0x000cb864 in poll ()
#1  0x000cd39c in __libc_enable_asynccancel ()
#2  0x4d9d9600 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 7 (Thread 1382.1393):
#0  0x000cbed4 in select ()
#1  0x000cd39c in __libc_enable_asynccancel ()
#2  0x00000000 in ?? ()

Thread 6 (Thread 1382.1392):
#0  0x000ac248 in pthread_cond_wait ()
#1  0x00010c6c in i2c_thread ()
#2  0x000a8b04 in start_thread ()
---Type <return> to continue, or q <return> to quit---
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 5 (Thread 1382.1391):
#0  0x000ad028 in __lll_lock_wait ()
#1  0x000aedd4 in __pthread_mutex_cond_lock ()
#2  0x000ac368 in pthread_cond_wait ()
#3  0x00010c6c in i2c_thread ()
#4  0x000a8b04 in start_thread ()
#5  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 4 (Thread 1382.1390):
#0  0x000ac248 in pthread_cond_wait ()
#1  0x00010c6c in i2c_thread ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 3 (Thread 1382.1389):
#0  0x000ad310 in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00011670 in sys_time_thread_main ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 2 (Thread 1382.1397):
#0  0x000c8144 in strlen ()
---Type <return> to continue, or q <return> to quit---
#1  0x000e087c in vfprintf ()
#2  0x000cdd4c in __printf_chk ()
#3  0x04f394bc in ?? ()
Backtrace stopped: frame did not save the PC

Thread 1 (Thread 1382.1382):
#0  0x000ac584 in pthread_cond_signal ()
#1  0x00010d80 in i2c_submit ()
#2  0x00037444 in i2c_blocking_transmit ()
#3  0x00014f74 in actuators_bebop_commit ()
#4  0x00022948 in main_periodic ()
#5  0x000268b8 in handle_periodic_tasks ()
#6  0x00010458 in main () at firmwares/rotorcraft/main.c:69

--------------------------------------------------------------------------------

Starting program: /home/tom/paparazzi/var/aircrafts/bebop2_opticflow/ap/ap.elf 
[New Thread 1398.1412]
[Switching to Thread 1398.1412]
0x000c8144 in strlen ()
(gdb) bt
#0  0x000c8144 in strlen ()
#1  0x000e087c in vfprintf ()
#2  0x000cdd4c in __printf_chk ()
#3  0x0473afce in ?? ()
Backtrace stopped: frame did not save the PC

(gdb) thread apply all bt
[New Thread 1398.1405]
[New Thread 1398.1406]
[New Thread 1398.1407]
[New Thread 1398.1408]
[New Thread 1398.1409]
[New Thread 1398.1410]
[New Thread 1398.1411]

Thread 9 (Thread 1398.1411):
#0  0x00045eec in image_difference ()
#1  0x00047370 in opticFlowLK ()
#2  0x00048a00 in calc_fast9_lukas_kanade ()
#3  0x0004abe8 in opticflow_calc_frame ()
#4  0x0004afc8 in opticflow_module_calc ()
#5  0x00038094 in cv_run_device ()
#6  0x0004ba64 in video_thread_function ()
#7  0x000a8b04 in start_thread ()
#8  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 8 (Thread 1398.1410):
#0  0x000cb864 in poll ()
#1  0x000cd39c in __libc_enable_asynccancel ()
#2  0x301b1600 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 7 (Thread 1398.1409):
#0  0x000cbed4 in select ()
#1  0x000cd39c in __libc_enable_asynccancel ()
#2  0x00000000 in ?? ()

Thread 6 (Thread 1398.1408):
#0  0x000ac248 in pthread_cond_wait ()
#1  0x00010c6c in i2c_thread ()
#2  0x000a8b04 in start_thread ()
---Type <return> to continue, or q <return> to quit---
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 5 (Thread 1398.1407):
#0  0x000cbdfc in ioctl ()
#1  0x00010b6c in i2c_thread ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 4 (Thread 1398.1406):
#0  0x000ac248 in pthread_cond_wait ()
#1  0x00010c6c in i2c_thread ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 3 (Thread 1398.1405):
#0  0x000ad310 in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00011670 in sys_time_thread_main ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 2 (Thread 1398.1412):
#0  0x000c8144 in strlen ()
#1  0x000e087c in vfprintf ()
#2  0x000cdd4c in __printf_chk ()
---Type <return> to continue, or q <return> to quit---
#3  0x0473afce in ?? ()
Backtrace stopped: frame did not save the PC

Thread 1 (Thread 1398.1398):
#0  0x0003760c in i2c_blocking_transceive ()
#1  0x00014cc0 in actuators_bebop_commit ()
#2  0x00022948 in main_periodic ()
#3  0x000268b8 in handle_periodic_tasks ()
#4  0x00010458 in main () at firmwares/rotorcraft/main.c:69

--------------------------------------------------------------------------------

Starting program: /home/tom/paparazzi/var/aircrafts/bebop2_opticflow/ap/ap.elf 
[New Thread 1421.1434]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 1421.1434]
0x000452f4 in image_to_grayscale ()
(gdb) info args
No symbol table info available.
(gdb) info locals
No symbol table info available.
(gdb) bt
#0  0x000452f4 in image_to_grayscale ()
#1  0x00048758 in calc_fast9_lukas_kanade ()
#2  0x0004abe8 in opticflow_calc_frame ()
#3  0x0004afc8 in opticflow_module_calc ()
#4  0x00038094 in cv_run_device ()
#5  0x0004ba64 in video_thread_function ()
#6  0x000a8b04 in start_thread ()
#7  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC
(gdb) source
source command requires file name of file to source.
(gdb) list
84	../sysdeps/unix/syscall-template.S: No such file or directory.
	in ../sysdeps/unix/syscall-template.S

--------------------------------------------------------------------------------

Starting program: /home/tom/paparazzi/var/aircrafts/bebop2_opticflow/ap/ap.elf 
[New Thread 1368.1382]
[Switching to Thread 1368.1382]
0x000c8144 in strlen ()
(gdb) bt
#0  0x000c8144 in strlen ()
#1  0x000e087c in vfprintf ()
#2  0x000cdd4c in __printf_chk ()
#3  0x03042a5a in ?? ()
Backtrace stopped: frame did not save the PC
(gdb) info locals
No symbol table info available.
(gdb) info threads
[New Thread 1368.1375]
[New Thread 1368.1376]
[New Thread 1368.1377]
[New Thread 1368.1378]
[New Thread 1368.1379]
[New Thread 1368.1380]
[New Thread 1368.1381]
  9 Thread 1368.1381  0x000a5cd0 in __udivsi3 ()
  8 Thread 1368.1380  0x000cb864 in poll ()
  7 Thread 1368.1379  0x000cbed4 in select ()
  6 Thread 1368.1378  0x000ac248 in pthread_cond_wait ()
  5 Thread 1368.1377  0x000ac248 in pthread_cond_wait ()
  4 Thread 1368.1376  0x000ac248 in pthread_cond_wait ()
  3 Thread 1368.1375  0x000ad310 in read () at ../sysdeps/unix/syscall-template.S:84
* 2 Thread 1368.1382  0x000c8144 in strlen ()
  1 Thread 1368.1368  0x000cd700 in clock_gettime ()
(gdb) thread apply all bt

Thread 9 (Thread 1368.1381):
#0  0x000a5cd0 in __udivsi3 ()
#1  0x00045b90 in image_subpixel_window ()
#2  0x00047360 in opticFlowLK ()
#3  0x00048a00 in calc_fast9_lukas_kanade ()
#4  0x0004abe8 in opticflow_calc_frame ()
#5  0x0004afc8 in opticflow_module_calc ()
#6  0x00038094 in cv_run_device ()
#7  0x0004ba64 in video_thread_function ()
#8  0x000a8b04 in start_thread ()
#9  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 8 (Thread 1368.1380):
#0  0x000cb864 in poll ()
#1  0x000cd39c in __libc_enable_asynccancel ()
#2  0xd915d900 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 7 (Thread 1368.1379):
#0  0x000cbed4 in select ()
#1  0x000cd39c in __libc_enable_asynccancel ()
#2  0x00000000 in ?? ()

Thread 6 (Thread 1368.1378):
#0  0x000ac248 in pthread_cond_wait ()
#1  0x00010c6c in i2c_thread ()
---Type <return> to continue, or q <return> to quit---
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 5 (Thread 1368.1377):
#0  0x000ac248 in pthread_cond_wait ()
#1  0x00010c6c in i2c_thread ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 4 (Thread 1368.1376):
#0  0x000ac248 in pthread_cond_wait ()
#1  0x00010c6c in i2c_thread ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC
Starting program: /home/tom/paparazzi/var/aircrafts/bebop2_opticflow/ap/ap.elf 
[New Thread 1359.1372]
[Switching to Thread 1359.1372]
0x000452f4 in image_to_grayscale ()
(gdb) bt
#0  0x000452f4 in image_to_grayscale ()
#1  0x00048758 in calc_fast9_lukas_kanade ()
#2  0x0004abe8 in opticflow_calc_frame ()
#3  0x0004afc8 in opticflow_module_calc ()
#4  0x00038094 in cv_run_device ()
#5  0x0004ba64 in video_thread_function ()
#6  0x000a8b04 in start_thread ()
#7  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

(gdb) thread apply all bt
[New Thread 1359.1366]
[New Thread 1359.1367]
[New Thread 1359.1368]
[New Thread 1359.1369]
[New Thread 1359.1370]
[New Thread 1359.1371]
[New Thread 1359.1373]

Thread 9 (Thread 1359.1373):
#0  0x000cbed4 in select ()
#1  0x000cd39c in __libc_enable_asynccancel ()
#2  0x00000000 in ?? ()

Thread 8 (Thread 1359.1371):
#0  0x000cb864 in poll ()
#1  0x000cd39c in __libc_enable_asynccancel ()
#2  0x43ea6d00 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 7 (Thread 1359.1370):
#0  0x000cbed4 in select ()
#1  0x000cd39c in __libc_enable_asynccancel ()
#2  0x00000000 in ?? ()

Thread 6 (Thread 1359.1369):
#0  0x000ac248 in pthread_cond_wait ()
#1  0x00010c6c in i2c_thread ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 5 (Thread 1359.1368):
#0  0x000cbdfc in ioctl ()
#1  0x00010b6c in i2c_thread ()
#2  0x000a8b04 in start_thread ()
---Type <return> to continue, or q <return> to quit---
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 4 (Thread 1359.1367):
#0  0x000ac248 in pthread_cond_wait ()
#1  0x00010c6c in i2c_thread ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 3 (Thread 1359.1366):
#0  0x000ad310 in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00011670 in sys_time_thread_main ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 2 (Thread 1359.1372):
#0  0x000452f4 in image_to_grayscale ()
#1  0x00048758 in calc_fast9_lukas_kanade ()
#2  0x0004abe8 in opticflow_calc_frame ()
#3  0x0004afc8 in opticflow_module_calc ()
#4  0x00038094 in cv_run_device ()
#5  0x0004ba64 in video_thread_function ()
#6  0x000a8b04 in start_thread ()
#7  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

---Type <return> to continue, or q <return> to quit---
Thread 1 (Thread 1359.1359):
#0  0x0003761c in i2c_blocking_transceive ()
#1  0x00014cc0 in actuators_bebop_commit ()
#2  0x00022948 in main_periodic ()
#3  0x000268b8 in handle_periodic_tasks ()
#4  0x00010458 in main () at firmwares/rotorcraft/main.c:69

--------------------------------------------------------------------------------

Starting program: /home/tom/paparazzi/var/aircrafts/bebop2_opticflow/ap/ap.elf 
[New Thread 1382.1397]
[Switching to Thread 1382.1397]
0x000c8144 in strlen ()
(gdb) bt
#0  0x000c8144 in strlen ()
#1  0x000e087c in vfprintf ()
#2  0x000cdd4c in __printf_chk ()
#3  0x04f394bc in ?? ()
Backtrace stopped: frame did not save the PC

(gdb) thread apply all bt
[New Thread 1382.1389]
[New Thread 1382.1390]
[New Thread 1382.1391]
[New Thread 1382.1392]
[New Thread 1382.1393]
[New Thread 1382.1395]
[New Thread 1382.1396]

Thread 9 (Thread 1382.1396):
#0  0x00045ee0 in image_difference ()
#1  0x00047370 in opticFlowLK ()
#2  0x00048a00 in calc_fast9_lukas_kanade ()
#3  0x0004abe8 in opticflow_calc_frame ()
#4  0x0004afc8 in opticflow_module_calc ()
#5  0x00038094 in cv_run_device ()
#6  0x0004ba64 in video_thread_function ()
#7  0x000a8b04 in start_thread ()
#8  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 8 (Thread 1382.1395):
#0  0x000cb864 in poll ()
#1  0x000cd39c in __libc_enable_asynccancel ()
#2  0x4d9d9600 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 7 (Thread 1382.1393):
#0  0x000cbed4 in select ()
#1  0x000cd39c in __libc_enable_asynccancel ()
#2  0x00000000 in ?? ()

Thread 6 (Thread 1382.1392):
#0  0x000ac248 in pthread_cond_wait ()
#1  0x00010c6c in i2c_thread ()
#2  0x000a8b04 in start_thread ()
---Type <return> to continue, or q <return> to quit---
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 5 (Thread 1382.1391):
#0  0x000ad028 in __lll_lock_wait ()
#1  0x000aedd4 in __pthread_mutex_cond_lock ()
#2  0x000ac368 in pthread_cond_wait ()
#3  0x00010c6c in i2c_thread ()
#4  0x000a8b04 in start_thread ()
#5  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 4 (Thread 1382.1390):
#0  0x000ac248 in pthread_cond_wait ()
#1  0x00010c6c in i2c_thread ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 3 (Thread 1382.1389):
#0  0x000ad310 in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00011670 in sys_time_thread_main ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 2 (Thread 1382.1397):
#0  0x000c8144 in strlen ()
---Type <return> to continue, or q <return> to quit---
#1  0x000e087c in vfprintf ()
#2  0x000cdd4c in __printf_chk ()
#3  0x04f394bc in ?? ()
Backtrace stopped: frame did not save the PC

Thread 1 (Thread 1382.1382):
#0  0x000ac584 in pthread_cond_signal ()
#1  0x00010d80 in i2c_submit ()
#2  0x00037444 in i2c_blocking_transmit ()
#3  0x00014f74 in actuators_bebop_commit ()
#4  0x00022948 in main_periodic ()
#5  0x000268b8 in handle_periodic_tasks ()
#6  0x00010458 in main () at firmwares/rotorcraft/main.c:69

--------------------------------------------------------------------------------

Starting program: /home/tom/paparazzi/var/aircrafts/bebop2_opticflow/ap/ap.elf 
[New Thread 1398.1412]
[Switching to Thread 1398.1412]
0x000c8144 in strlen ()
(gdb) bt
#0  0x000c8144 in strlen ()
#1  0x000e087c in vfprintf ()
#2  0x000cdd4c in __printf_chk ()
#3  0x0473afce in ?? ()
Backtrace stopped: frame did not save the PC

(gdb) thread apply all bt
[New Thread 1398.1405]
[New Thread 1398.1406]
[New Thread 1398.1407]
[New Thread 1398.1408]
[New Thread 1398.1409]
[New Thread 1398.1410]
[New Thread 1398.1411]

Thread 9 (Thread 1398.1411):
#0  0x00045eec in image_difference ()
#1  0x00047370 in opticFlowLK ()
#2  0x00048a00 in calc_fast9_lukas_kanade ()
#3  0x0004abe8 in opticflow_calc_frame ()
#4  0x0004afc8 in opticflow_module_calc ()
#5  0x00038094 in cv_run_device ()
#6  0x0004ba64 in video_thread_function ()
#7  0x000a8b04 in start_thread ()
#8  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 8 (Thread 1398.1410):
#0  0x000cb864 in poll ()
#1  0x000cd39c in __libc_enable_asynccancel ()
#2  0x301b1600 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 7 (Thread 1398.1409):
#0  0x000cbed4 in select ()
#1  0x000cd39c in __libc_enable_asynccancel ()
#2  0x00000000 in ?? ()

Thread 6 (Thread 1398.1408):
#0  0x000ac248 in pthread_cond_wait ()
#1  0x00010c6c in i2c_thread ()
#2  0x000a8b04 in start_thread ()
---Type <return> to continue, or q <return> to quit---
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 5 (Thread 1398.1407):
#0  0x000cbdfc in ioctl ()
#1  0x00010b6c in i2c_thread ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 4 (Thread 1398.1406):
#0  0x000ac248 in pthread_cond_wait ()
#1  0x00010c6c in i2c_thread ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 3 (Thread 1398.1405):
#0  0x000ad310 in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00011670 in sys_time_thread_main ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 2 (Thread 1398.1412):
#0  0x000c8144 in strlen ()
#1  0x000e087c in vfprintf ()
#2  0x000cdd4c in __printf_chk ()
---Type <return> to continue, or q <return> to quit---
#3  0x0473afce in ?? ()
Backtrace stopped: frame did not save the PC

Thread 1 (Thread 1398.1398):
#0  0x0003760c in i2c_blocking_transceive ()
#1  0x00014cc0 in actuators_bebop_commit ()
#2  0x00022948 in main_periodic ()
#3  0x000268b8 in handle_periodic_tasks ()
#4  0x00010458 in main () at firmwares/rotorcraft/main.c:69

--------------------------------------------------------------------------------

Starting program: /home/tom/paparazzi/var/aircrafts/bebop2_opticflow/ap/ap.elf 
[New Thread 1421.1434]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 1421.1434]
0x000452f4 in image_to_grayscale ()
(gdb) info args
No symbol table info available.
(gdb) info locals
No symbol table info available.
(gdb) bt
#0  0x000452f4 in image_to_grayscale ()
#1  0x00048758 in calc_fast9_lukas_kanade ()
#2  0x0004abe8 in opticflow_calc_frame ()
#3  0x0004afc8 in opticflow_module_calc ()
#4  0x00038094 in cv_run_device ()
#5  0x0004ba64 in video_thread_function ()
#6  0x000a8b04 in start_thread ()
#7  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC
(gdb) source
source command requires file name of file to source.
(gdb) list
84	../sysdeps/unix/syscall-template.S: No such file or directory.
	in ../sysdeps/unix/syscall-template.S

--------------------------------------------------------------------------------

Starting program: /home/tom/paparazzi/var/aircrafts/bebop2_opticflow/ap/ap.elf 
[New Thread 1368.1382]
[Switching to Thread 1368.1382]
0x000c8144 in strlen ()
(gdb) bt
#0  0x000c8144 in strlen ()
#1  0x000e087c in vfprintf ()
#2  0x000cdd4c in __printf_chk ()
#3  0x03042a5a in ?? ()
Backtrace stopped: frame did not save the PC
(gdb) info locals
No symbol table info available.
(gdb) info threads
[New Thread 1368.1375]
[New Thread 1368.1376]
[New Thread 1368.1377]
[New Thread 1368.1378]
[New Thread 1368.1379]
[New Thread 1368.1380]
[New Thread 1368.1381]
  9 Thread 1368.1381  0x000a5cd0 in __udivsi3 ()
  8 Thread 1368.1380  0x000cb864 in poll ()
  7 Thread 1368.1379  0x000cbed4 in select ()
  6 Thread 1368.1378  0x000ac248 in pthread_cond_wait ()
  5 Thread 1368.1377  0x000ac248 in pthread_cond_wait ()
  4 Thread 1368.1376  0x000ac248 in pthread_cond_wait ()
  3 Thread 1368.1375  0x000ad310 in read () at ../sysdeps/unix/syscall-template.S:84
* 2 Thread 1368.1382  0x000c8144 in strlen ()
  1 Thread 1368.1368  0x000cd700 in clock_gettime ()
(gdb) thread apply all bt

Thread 9 (Thread 1368.1381):
#0  0x000a5cd0 in __udivsi3 ()
#1  0x00045b90 in image_subpixel_window ()
#2  0x00047360 in opticFlowLK ()
#3  0x00048a00 in calc_fast9_lukas_kanade ()
#4  0x0004abe8 in opticflow_calc_frame ()
#5  0x0004afc8 in opticflow_module_calc ()
#6  0x00038094 in cv_run_device ()
#7  0x0004ba64 in video_thread_function ()
#8  0x000a8b04 in start_thread ()
#9  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 8 (Thread 1368.1380):
#0  0x000cb864 in poll ()
#1  0x000cd39c in __libc_enable_asynccancel ()
#2  0xd915d900 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 7 (Thread 1368.1379):
#0  0x000cbed4 in select ()
#1  0x000cd39c in __libc_enable_asynccancel ()
#2  0x00000000 in ?? ()

Thread 6 (Thread 1368.1378):
#0  0x000ac248 in pthread_cond_wait ()
#1  0x00010c6c in i2c_thread ()
---Type <return> to continue, or q <return> to quit---
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 5 (Thread 1368.1377):
#0  0x000ac248 in pthread_cond_wait ()
#1  0x00010c6c in i2c_thread ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 4 (Thread 1368.1376):
#0  0x000ac248 in pthread_cond_wait ()
#1  0x00010c6c in i2c_thread ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 3 (Thread 1368.1375):
#0  0x000ad310 in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00011670 in sys_time_thread_main ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 2 (Thread 1368.1382):
#0  0x000c8144 in strlen ()
#1  0x000e087c in vfprintf ()
---Type <return> to continue, or q <return> to quit---
#2  0x000cdd4c in __printf_chk ()
#3  0x03042a5a in ?? ()
Backtrace stopped: frame did not save the PC

Thread 1 (Thread 1368.1368):
#0  0x000cd700 in clock_gettime ()
#1  0x0001194c in get_sys_time_usec ()
#2  0x0005adec in imu_bebop_event ()
#3  0x0001045c in main () at firmwares/rotorcraft/main.c:70
Thread 3 (Thread 1368.1375):
#0  0x000ad310 in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00011670 in sys_time_thread_main ()
#2  0x000a8b04 in start_thread ()
#3  0x000cd168 in ?? ()
Backtrace stopped: frame did not save the PC

Thread 2 (Thread 1368.1382):
#0  0x000c8144 in strlen ()
#1  0x000e087c in vfprintf ()
---Type <return> to continue, or q <return> to quit---
#2  0x000cdd4c in __printf_chk ()
#3  0x03042a5a in ?? ()
Backtrace stopped: frame did not save the PC

Thread 1 (Thread 1368.1368):
#0  0x000cd700 in clock_gettime ()
#1  0x0001194c in get_sys_time_usec ()
#2  0x0005adec in imu_bebop_event ()
#3  0x0001045c in main () at firmwares/rotorcraft/main.c:70
```

**Comment by OpenUAS** [comment]
Shall we retest after PR #2364  is honored? Would be good to have pinpointed cause before TU Course 2019 started though

**Comment by OpenUAS** [comment]
OK @kirkscheper will fix #2364  after a "Stable" release, will get an interesting January before TU course 2019 starts...

**Comment by kirkscheper** [comment]
This may be connected to #2361 #2378, a fix has been pushed for an error with the spi which is used by the sonar. The error would only surface under some circumstances which would explain why I couldn't recreate this. Can you test your airframe with master/rebase on master and let us know if you still have this issue?

**Comment by tomvand** [comment]
Re-tested today with da3e040 and master (9ba84b8). The problem still occurs, I could get a segfault during takeoff with both commits. I could not replicate it above the textured mat, though.

**Comment by tomvand** [comment]
Reopening this, the segfault still occurs in master with the bebop2_opticflow aircraft in the example conf.

ap.elf now consistently crashes in v4l2.c line 102. The `dev` struct appears incorrect, with an unreadable name and height of 0. The dev width changes between runs, so I wouldn't be surprised if this struct gets overwritten from somewhere else...

Crash log 1:
```
/data/ftp/internal_000/paparazzi # ./gdb ap.elf 
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-none-linux-gnueabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ap.elf...done.
(gdb) r
Starting program: /data/ftp/internal_000/paparazzi/ap.elf 
[New LWP 1424]
[New LWP 1425]
[New LWP 1426]
Current schedparam: policy 0, prio 0
Current schedparam: policy 0, prio 0
New schedparam: policy 1, prio 29
New schedparam: policy 1, prio 11
[New LWP 1427]
Current schedparam: policy 0, prio 0
New schedparam: policy 1, prio 10
[New LWP 1428]
Current schedparam: policy 0, prio 0
New schedparam: policy 1, prio 10
Current schedparam: policy 0, prio 0
New schedparam: policy 1, prio 10
[New LWP 1429]
Current schedparam: policy 0, prio 0
New schedparam: policy 1, prio 10
[New LWP 1430]
[New LWP 1431]
[video_thread-/dev/video0] Set nice level to 5.
[v4l2-capture] Select timeout on /dev/video0
ap.elf: pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.

Thread 9 "v4l2" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 1431]
v4l2_capture_thread (data=0x199c58) at modules/computer_vision/lib/v4l/v4l2.c:102
102     modules/computer_vision/lib/v4l/v4l2.c: No such file or directory.
(gdb) bt
#0  v4l2_capture_thread (data=0x199c58) at modules/computer_vision/lib/v4l/v4l2.c:102
#1  0x000aec30 in start_thread (arg=0xb35ff300) at pthread_create.c:335
#2  0x000d3398 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) info locals
sr = <optimized out>
now_ts = 33662766
prev_idx = <optimized out>
dev = 0x199c58
buf = {index = 3, type = 1, bytesused = 115200, flags = 8197, field = 1, timestamp = {tv_sec = 1314, tv_usec = 237549}, timecode = {type = 0, flags = 0, frames = 0 '\000', seconds = 0 '\000', 
    minutes = 0 '\000', hours = 0 '\000', userbits = "\000\000\000"}, sequence = 2627, memory = 1, m = {offset = 356352, userptr = 356352, planes = 0x57000 <stateCalcVerticalWindspeed_f+64>, 
    fd = 356352}, length = 115200, reserved2 = 0, reserved = 0}
tv = {tv_sec = 1, tv_usec = 988806}
fds = {fds_bits = {1024, 0 <repeats 31 times>}}
__PRETTY_FUNCTION__ = "v4l2_capture_thread"
(gdb) print *dev
$1 = {name = 0x199c90 "\336", fd = 10, thread = 215, w = 26, h = 0, buffers_cnt = 5 '\005', buffers_deq_idx = 0 '\000', mutex = {__data = {__lock = 1, __count = 206, __owner = 72, __kind = 0, 
      __nusers = 0, {__spins = 206, __list = {__next = 0xce}}}, __size = "\001\000\000\000\316\000\000\000H", '\000' <repeats 11 times>, "\316\000\000", __align = 1}, buffers = 0x25}
(gdb) info args   
data = 0x199c58
(gdb) info threads
  Id   Target Id         Frame 
  1    LWP 1415 "ap.elf" 0x000541a8 in pprz_check_and_parse (dev=dev@entry=0x1840c8 <udp0+524>, trans=trans@entry=0x189158 <pprz_tp>, buf=buf@entry=0x1947b8 <dl_buffer> "", 
    msg_available=msg_available@entry=0x1947b0 <dl_msg_available>) at /home/mario/paparazzi/var/share/pprzlink/src/pprz_transport.c:191
  2    LWP 1424 "sys_time" 0x000b3440 in read () at ../sysdeps/unix/syscall-template.S:84
  3    LWP 1425 "uart"   0x000d2104 in select ()
  4    LWP 1426 "i2c"    0x000b2374 in __pthread_cond_wait (cond=0x183348 <i2c0_thread+24>, cond@entry=0x0, mutex=mutex@entry=0x183330 <i2c0_thread>) at pthread_cond_wait.c:186
  5    LWP 1427 "i2c"    0x000b2374 in __pthread_cond_wait (cond=0x1833b0 <i2c1_thread+24>, cond@entry=0x0, mutex=mutex@entry=0x183398 <i2c1_thread>) at pthread_cond_wait.c:186
  6    LWP 1428 "i2c"    0x000d202c in ioctl ()
  7    LWP 1429 "udp"    0x000d2104 in select ()
  8    LWP 1430 "camera" 0x000b3824 in raise (sig=6) at ../sysdeps/unix/sysv/linux/pt-raise.c:35
* 9    LWP 1431 "v4l2"   v4l2_capture_thread (data=0x199c58) at modules/computer_vision/lib/v4l/v4l2.c:102
(gdb) 
```

Crash log 2:
```
/data/ftp/internal_000/paparazzi # ./gdb ap.elf 
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-none-linux-gnueabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ap.elf...done.
(gdb) r
Starting program: /data/ftp/internal_000/paparazzi/ap.elf 
[New LWP 1322]
Current schedparam: policy 0, prio 0
New schedparam: policy 1, prio 29
[New LWP 1323]
Current schedparam: policy 0, prio 0
New schedparam: policy 1, prio 10
[New LWP 1324]
Current schedparam: policy 0, prio 0
New schedparam: policy 1, prio 10
[New LWP 1325]
Current schedparam: policy 0, prio 0
New schedparam: policy 1, prio 10
[New LWP 1326]
[New LWP 1327]
Current schedparam: policy 0, prio 0
New schedparam: policy 1, prio 10
[New LWP 1328]
[New LWP 1329]
[video_thread-/dev/video0] Set nice level to 5.
[v4l2-capture] Select timeout on /dev/video0
ap.elf: pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.

Thread 9 "v4l2" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 1329]
v4l2_capture_thread (data=0x195c58) at modules/computer_vision/lib/v4l/v4l2.c:102
102     modules/computer_vision/lib/v4l/v4l2.c: No such file or directory.
(gdb) bt
#0  v4l2_capture_thread (data=0x195c58) at modules/computer_vision/lib/v4l/v4l2.c:102
#1  0x000ac028 in start_thread (arg=0xb356e300) at pthread_create.c:335
#2  0x000d0748 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) info locals
sr = <optimized out>
now_ts = 227464515
prev_idx = <optimized out>
dev = 0x195c58
buf = {index = 0, type = 1, bytesused = 115200, flags = 8197, field = 1, timestamp = {tv_sec = 313, tv_usec = 39419}, timecode = {type = 0, flags = 0, frames = 0 '\000', seconds = 0 '\000', 
    minutes = 0 '\000', hours = 0 '\000', userbits = "\000\000\000"}, sequence = 19920, memory = 1, m = {offset = 0, userptr = 0, planes = 0x0, fd = 0}, length = 115200, reserved2 = 0, reserved = 0}
tv = {tv_sec = 1, tv_usec = 988810}
fds = {fds_bits = {1024, 0 <repeats 31 times>}}
__PRETTY_FUNCTION__ = "v4l2_capture_thread"
(gdb) print *dev
$1 = {name = 0x195c90 "\324", fd = 10, thread = 235, w = 22, h = 0, buffers_cnt = 5 '\005', buffers_deq_idx = 1 '\001', mutex = {__data = {__lock = 1, __count = 223, __owner = 28, __kind = 0, 
      __nusers = 0, {__spins = 216, __list = {__next = 0xd8}}}, __size = "\001\000\000\000\337\000\000\000\034", '\000' <repeats 11 times>, "\330\000\000", __align = 1}, buffers = 0x20}
(gdb) 
```

**Comment by tomvand** [comment]
oops now actually reopening...

**Comment by OpenUAS** [comment]
Closed with pull #2411
